version: '3.8'
services:
    db:
        image: mysql:8.0
        environment:
            - MYSQL_DATABASE=laravel_survey
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - '3306:3306'
        volumes:
            - .docker/db:/var/lib/mysql
        networks:
            - mysql-compose-network
    adminer:
        image: adminer
        ports:
            - 8080:8080
        networks:
            - mysql-compose-network


networks:
    mysql-compose-network:
        driver: bridge
